name: Release
on:
  push:
    branches:
      - "main"
      - "next"

jobs:
  checks:
    uses: ./.github/workflows/checks.yaml

  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
